#This docker compose file executes the previously initialized node in the Tahoe-LAFS Grid.
version: "3.8"
services:
   storageNode:
    image: "derkades/tahoe-lafs:dev"
    networks:
      - tahoe_network
    configs:
      - source: storage_conf
        target: /data/tahoe.cfg
      - source: introducer_furl
        target: /data/private/introducers.yaml
    environment:
      - TAHOE_TUB_PORT=${TAHOE_TUB_PORT}
      - TAHOE_INTRODUCER_FURL=${TAHOE_INTRODUCER_FURL}
    deploy:
      mode: global
      resources:
        limits:
          cpus: "0.25"
          memory: 1G 
      placement:
        constraints:
          - node.labels.tahoe.storage == true
    volumes:
      - type: volume
        source: tahoe_storage_config
        target: /data
      - type: bind
        source: ${TAHOE_LOG_DIR}
        target: /data/logs
      - type: bind
        source: ${TAHOE_STORAGE_DIR}
        target: /storage
volumes:
  tahoe_storage_config:
networks:
  tahoe_network:
    driver: overlay
configs:
  storage_conf:
    external: true
  introducer_furl:
    external: true
