#This docker compose file executes the previously initialized node in the Tahoe-LAFS Grid.
version: "3.8"
services:
   storageNode:
    image: goglu6/tahoe-lafs-storage:dev
    networks:
      - tahoe_network
    configs:
      - source: storage_conf
        target: /data/tahoe.cfg
      - source: introducer_furl
        target: /data/private/introducers.yaml
    environment:
      - TAHOE_TUB_PORT=${TAHOE_TUB_PORT}
    deploy:
      mode: global
      resources:
        limits:
          cpus: "1"
          memory: 2G 
      placement:
        constraints:
          - node.labels.tahoe.storage == true
    volumes:
      - type: bind
        source: ${TAHOE_LOG_DIR}
        target: /data/logs
      - type: bind
        source: ${TAHOE_STORAGE_DIR}
        target: /storage
networks:
  tahoe_network:
    driver: overlay
    external: true
configs:
  storage_conf:
    external: true
  introducer_furl:
    external: true
