#This docker compose file executes sftp client nodes.
#Increasing the replicas count will spawn many identical node.
version: "3.8"
services:
   client-sftp-node:
    image: goglu6/tahoe-lafs-node:latest
    ports:
      - target: ${TAHOE_SSH_PORT}
        published: ${TAHOE_SSH_PORT}
        protocol: tcp
        mode: host
    networks:
      -  tahoe-grid-network
    secrets:
      - private_key_ssh
      - public_key_ssh
      - accounts_sftp
    configs:
      - source: sftp_conf
        target: /data/tahoe.cfg
      - source: introducer_furl
        target: /data/private/introducers.yaml
    environment:
      - TAHOE_SSH_PORT=${TAHOE_SSH_PORT}
      - TAHOE_TUB_PORT=${TAHOE_TUB_PORT}
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 2G 
    volumes:
      - type: volume
        source: log-client-sftp
        target: /data/logs
volumes:
  log-client-sftp:
secrets:
  private_key_ssh:
      file: ../tahoe-secrets-templates/private.key
  public_key_ssh:
      file: ../tahoe-secrets-templates/public.key
  accounts_sftp:
    file: ../tahoe-secrets-templates/sftp-accounts.tmpl
configs:
  sftp_conf:
    file: ../tahoe-config-templates/client-sftp-config.tmpl
    template_driver: golang
  introducer_furl:
    file: ../tahoe-config-templates/introducer-furl.tmpl
    template_driver: golang
networks:
   tahoe-grid-network:
    driver: overlay
    external: true