#This docker compose file executes the previously initialized node in the Tahoe-LAFS Grid.
version: "3.8"
services:
   storage-node:
    image: goglu6/tahoe-lafs-storage:dev
    hostname: "{{.Node.ID}}.{{.Task.ID}}"
    networks:
      - tahoe-grid-network
    configs:
      - source: storage-conf
        target: /data/tahoe.cfg
      - source: introducer_furl
        target: /data/private/introducers.yaml
    environment:
      - TAHOE_TUB_PORT=${TAHOE_TUB_PORT}
    deploy:
      mode: global
      resources:
        limits:
          cpus: "1"
          memory: 2G 
      placement:
        constraints:
          - node.labels.tahoe.storage == true
    volumes:
      - type: volume
        source: log-storage
        target: /data/logs
      - type: bind
        source: ${TAHOE_STORAGE_DIR}
        target: /storage
volumes:
  log-storage:
configs:
  storage-conf:
    file: ../tahoe-config-templates/storageNode-TCP-noGC.conf.tmpl
    template_driver: golang
  introducer_furl:
      file: ../tahoe-config-templates/introducer-furl.tmpl
      template_driver: golang
networks:
  tahoe-grid-network:
    driver: overlay
    external: true